### ISSUE TITLE
Memory leak when using pulse width triggering

### ISSUE THREAD

**Issue by ZPMU** [saleae/gitbook-docs#13]
I want to take a measure when a particular signal (normally '1') becomes '0'. So I switched to trigger on falling edge of that signal. In preferences I adjusted the pretrigger buffer to 10 s.

When I start the measurement I observe "Memory Used" displayed creeps up for about 10 s (not timed exactly) and then stops at a constant value. This looks reasonable, because it is the memory used for pretrigger buffer, and the other inputs see a continuously chattering SPI with more or less constant data rate. So far, so good.

Then, to prevent false triggering due to small errant pulses, I switched from normal falling edge triggering to neg. pulse triggering. I chose min. width 0.1 s and max. width "n/a". (On intended triggering the particular signal becomes and stays at '0'). Now "Memory Used" creeps and creeps (rate about 4 MB/s), being consistent with used memory display on windows task-manager. When canceling the measurement, it drops down about to the value before starting measurement. This happens as well at the moment the trigger fires and the actual measurement starts. (Of course, it then rises again in order to save measuring data.)

When finally running out of memory (Logic claims to use more memory than physically installed), the computer becomes choppy (supposedly due to swapping) and eventually Logic complains about being "not able to keep up with this sample rate". After acknowledge the message, Logic needed half a minute or so to recuperate, but it finally frees the memory and becomes responsive again.

SW: Logic 1.2.18, Win 7
HW: Logic 16, 8 channels active, used at 12.5 MS/s

Regards, Peter

**Comment by timreyes** [comment]
Hi Peter,

Sorry to hear this...

This is extremely odd behavior. I wasn't able to reproduce this issue, though I may be missing some information.

Do you mind sending me (Tim Reyes) an email at support@saleae.com? Please share the following in the email:
- Can you try with the latest beta software below? Let me know if it solves it:
https://support.saleae.com/logic-software/latest-beta-release
- Can you take a screenshot of the "Waiting for trigger..." window? Preferably when the memory usage has gotten high.
- Do you have any Analyzers attached? Please disable them if so.

I'll go ahead and close this Github issue. Let's continue talking through email.

**Comment by ZPMU** [comment]
Hi Tim,

thanks for your reply.

When using Version 1.2.18, there is a parameter shown named "Trigger Search Backlog". This shows "0" in case of edge triggering, but in case of pulse triggering (with max. width "n/a") it shows the same number as under "Digital Samples Collected" (see Attachment) and also counts up the same way, of course. In order to take the screenshot, I've waited some minutes, albeit this is far away from eating up all the 32 GiB of memory.
There were some Analyzers active (an I²C and two UART ones). I've removed them, but the problem persists.

I've tested 1.2.29 beta -- now this problem has gone. I'm happy with this, so mind using this as my standard program instead of 1.2.18?

There are some other minor issues that caught my eyes:
* When installing the beta version, I chose another directory, assuming that in the end the final and the beta version will be installed in parallel. But during installing, the beta version apparently removed the older final version. But as long as the beta version doesn't seems to be touchy …
* The beta version shows up with real time scrolling the traces in a DSO-like fashion. Looks great, but I got one proposal: As soon as the traces becomes longer than my window, a scrollbar appears. If I try to zoom out, there is a limit when the current length of the traces fits screen. It would be nice if I could zoom out even further, so that there is a visual empty range, becoming filled again gradually.
* It would be nice if there is an alternative for duration. Instead of giving a number of seconds or samples to record, there should be optionally a memoryesk limit like "stop when … G/M/kBytes used" or "stop when there is less than … G/M/kBytes free physical memory left". They can be simultaneous active, in a manner like "whichever occurs first".

HTH & regards, Peter


________________________________
http://www.zera.de

ZERA GmbH, Hauptstrasse 392, 53639 Koenigswinter
Geschaeftsfuehrer: Horst Waechter
Sitz der Gesellschaft: Koenigswinter; Handelsregister HRB 7073
Registergericht: Amtsgericht Siegburg.

Diese E-Mail enthält vertrauliche oder rechtlich geschützte Informationen. Wenn Sie nicht der beabsichtigte Empfänger sind, informieren Sie bitte sofort den Absender und löschen Sie diese E-Mail. Das unbefugte Kopieren dieser E-Mail oder die unbefugte Weitergabe der enthaltenen Informationen ist nicht gestattet.

The information contained in this message is confidential or protected by law. If you are not the intended recipient, please contact the sender and delete this message. Any unauthorised copying of this message or unauthorised distribution of the information contained herein is prohibited.

-----------------------------------------------------------------

**Comment by timreyes** [comment]
Hi Peter,

Thanks for the heads up. Yes please use 1.2.29. It is considered stable. We just have not had the time to put it up on our main downloads page. There's a bit more work involved with doing that, which has nothing to do with the software's functionality.

Notes below on your 3 points.
1. You cannot install 2 versions of the software at the same time. I suggest installing 1.2.29, then downloading the standalone version of 1.2.18 below if you really need the older version:
https://support.saleae.com/logic-software/latest-stable-release-download

2. Thanks for the feedback. I agree. The real time view is primitive in 1.2.29. We're working on making it much better! It's not ready yet, but here's a preview:
https://discuss.saleae.com/

3. This is a really interesting point. Do you mind posting this up on our ideas site? I think it's a great idea that hasn't been posted yet. Once it's up there, I'm happy to personally bring it up with our team.
https://ideas.saleae.com/#1

Best regards,
Tim
