### ISSUE TITLE
cannot keep up to this sample rate

### ISSUE THREAD

**Issue by guy-maker** [saleae/gitbook-docs#15]
I keep seeing this error: 

![image](https://user-images.githubusercontent.com/59409247/74335451-f34b6000-4da4-11ea-9fb3-ab725c7ad2ef.png)

**Comment by guy-maker** [comment]
in every sampling rate

**Comment by timreyes** [comment]
Sorry for the trouble with this... I'd like to get a support ticket open for you via email. We can solve this through that channel. I'll close this Github issue for now and will wait for your email.

In the meantime, can you:
1. Run the troubleshooting steps here: https://support.saleae.com/troubleshooting/device-not-able-to-keep-up
2. Send an email to support@saleae.com
3. Share with us the results of the tests and the information requested in the support article.

Looking forward to getting to the bottom of this for you.
