### ISSUE TITLE
Sample Rate Always Too High

### ISSUE THREAD

**Issue by wolfenstein11x** [saleae/gitbook-docs#16]
Everytime I hit start, I get the message "We're sorry, but the device was not able to keep up with this sample rate. If you continue to see this message, please contace Saleae technical support."

edit: It happens ALMOST everytime. Sometimes it works fine, but I don't know why.

**Comment by timreyes** [comment]
Sorry to hear this. Our GitHub issues list is specifically for documentation issues only, so I'm going to close this issue now.

In the meantime, can you send a message to me (Tim), via the link below? I'm happy to help out through our support channel.
https://contact.saleae.com/hc/en-us/requests/new

Please run through the tests in the following article and let me know the detailed results once you send in your message. 
https://support.saleae.com/troubleshooting/device-not-able-to-keep-up

Sorry again for the trouble with this...
