### ISSUE TITLE
Can Saleae product can monitor SPI data in real time?

### ISSUE THREAD

**Issue by tienlocnguyen** [saleae/gitbook-docs#17]
I'm finding solution for my testing solution. It's required to capture SPI data in real time with following scenario:
PC send command to DUT via CAN, GPIO,... -> DUT send something via SPI -> PC monitor SPI sent by DUT and judge test case pass or fail by data correctness and response time. A test case may contain many send/monitor sequence.
I investigated your product and saw that it support slightly different scenario: PC start monitor SPI at start of test case, stop after finish and then can validate SPI logged data.
My question is how can adapt current supported feature of Saleae product with my scenario?

**Comment by timreyes** [comment]
Happy to help! I will close this issue for now - The Issues on this page is for documentation issues only.

Can you send us an email using the link below?
https://contact.saleae.com/hc/en-us/requests/new

I'm happy to chat with you there. Specifically, if you are looking to set up Saleae Logic in an automated environment, this is certainly doable via our Automation API. More information below:
https://support.saleae.com/saleae-api-and-sdk/socket-api

Hope this helps! Looking forward to chat more via email in case you need any help with getting that set up.
