### ISSUE TITLE
Need to unplug/replug USB cable after power failure

### ISSUE THREAD

**Issue by SteveCan1** [saleae/gitbook-docs#20]
Hi,

We're currently doing a lot of our work remotely, and have experienced some power failures in our remote lab over the last little while. Each time, the PC on to which the Saleae analyzer is connected has trouble reconnecting and gives us the following pop-up:

![image](https://user-images.githubusercontent.com/67252809/89787073-e5279380-daea-11ea-84fd-3ac97c2e9132.png)

("Please unplug, and then reconnect your device")

I was just wondering if there is a way to avoid having to perform this physical manipulation in order to continue using the device... When it occurs, we have to see if somebody on-site is able to go and perform the operation.

Is there another way to re-initialize the connection _without_ having to physically manipulate the USB cable?

This is not really a show-stopper or very serious issue, however it would certainly add to the perceived reliability of the device if we didn't have to perform this operation.

Thanks for your help!

Steve

(By the way, LOVE the device!!!)

**Comment by timreyes** [comment]
Hi Steve,

Thanks for reporting this, and sorry for all the trouble. Unfortunately, besides disconnecting and reconnecting the hardware, we don't have a great way of recovering from this failure in our current implementation of our USB layer.

This is something that is on our minds for next-gen hardware. Sorry I don't have a remote-friendly solution for this...

By the way, feel free to reach out to me using the link below in case you'd like to discuss anything else further:
https://contact.saleae.com/hc/en-us/requests/new

This Gihub Issues is typically for typos or misinformation on our support site.

BR,
Tim
