### ISSUE TITLE
Would like to "Zoom-to-window". Can it be done?

### ISSUE THREAD

**Issue by SteveCan1** [saleae/gitbook-docs#21]
Hi,

I'm trying to compare two traces and would like to place them "side-by-side" to facilitate a visual comparison. Is there a way to zoom a capture window to a region defined by dragging the mouse cursor? This would allow me to place the captures in a single window, one on top of the other, and perform a visual comparison with the events better aligned...

Thanks for your help.

Steve

**Comment by timreyes** [comment]
Hi Steve,

We might have a solution for this in our [Logic v2 Software](https://ideas.saleae.com/f/changelog/).

Could you try it out? At the bottom-left of the software, you can set the exact time-scale per 100 pixels, which you can set equally for 2 different capture windows.

In case you'd like to discuss further, please contact me here and I'll be happy to help!
https://contact.saleae.com/hc/en-us/requests/new

We typically reserve this Issues list for misinformation and typos on our support site.

BR,
Tim
