### ISSUE TITLE
voltage measurement doesn't appear to be linear.  Is that expected?

### ISSUE THREAD

**Issue by ccrome** [saleae/gitbook-docs#25]
Hi there,
  I have a Logic Pro 16 (Red), and am measuring battery charge voltage.  The charging curve looks like this:

![image](https://user-images.githubusercontent.com/286973/93128473-65aa5880-f684-11ea-8aea-22ea2ea94b0f.png)

You can see that it stays level at one voltage, then quick takes 4 steps to the next voltage, then stays for a while.  I know for sure that the actual voltage is a smooth curve (except for  those periodic 120 sec interval spikes), and that it doesn't have that stair step pattern.  

I know we're right down at the A/D converter resolution, and it looks like it's not quite accurate down to the LSB.   Not a big problem for me, but wanted to know if that's normal.

**Comment by timreyes** [comment]
Hi, this is certainly strange. Our Logic Pro 16 is rated at 5mV per LSB. Specs below:
https://support.saleae.com/faq/technical-faq/resolution-of-the-analog-inputs

Typically, this issues list is reserved for support page updates and typos. I'm going to close this issue now, but let's continue our conversation via email. Could you send me an email at support@saleae.com? Let us know that you spoke to me (Tim) via Github. I'd like to grab the following from you:

- The .sal file (capture file) that shows the issue
- Let us know your test setup in as much detail as possible, such that you can confirm how you are sure that the actual voltage is a smooth curve.
- Let us know if the same issue appears in our older software below:
https://support.saleae.com/logic-software/legacy-software/latest-beta-release
- Which version of Logic 2 software are you running? Same issues in the latest? see below:
https://ideas.saleae.com/f/changelog/

Looking forward to receiving your email.
