### ISSUE TITLE
Logic 2 - Device LED

### ISSUE THREAD

**Issue by patrick-compass** [saleae/gitbook-docs#29]
The user guide describes where to change the LED color using Logic 1.x, but not for Logic 2.

We use the LED to help us connect the right leads up when using multiple Saleae devices at the same time.

**Comment by timreyes** [comment]
Thanks for the feedback and for describing your need. You are right. This is something we certainly need in the Logic 2 software, but unfortunately is lower priority at the moment. I made the following updates for now to our support documentation. 

- https://support.saleae.com/user-guide/using-logic/capture-settings (Added a note about LED settings not being supported atm in Logic 2)
- https://ideas.saleae.com/b/feature-requests/change-the-led-color-on-the-unit/ (Added your comment to the idea we are tracking right now. Feel free to add your vote or any other comments you have! We appreciate you describing your use case btw. Very helpful)
