### ISSUE TITLE
Demo Application Links wrong

### ISSUE THREAD

**Issue by shantanuraje** [saleae/gitbook-docs#3]
The demo application links point to your localhost machine.

**Comment by Marcus10110** [comment]
Thanks for reporting this! @timreyes I believe the links in question are here:
https://support.saleae.com/tutorials/example-projects/how-to-analyze-spi#run-demo-application-3

**Comment by timreyes** [comment]
Sorry about that! I'm waiting on our writer to provide the proper links. Once I get that, I'll update it right away. In the meantime, I'll leave this open.

**Comment by timreyes** [comment]
The links are now fixed.
