### ISSUE TITLE
analyzer-specific data in demo mode

### ISSUE THREAD

**Issue by pierremolinaro** [saleae/gitbook-docs#34]
Hello,

I was quite surprised by the default behavior of Logic2 in demo mode: "By default, when an analyzer is added to digital channels while in Demo mode, the simulation data on those digital channels will continue to contain random transitions and will not contain analyzer-specific data"

Having random data is of little interest, except perhaps to the analyzer designer to test robustness against random data.

Put yourself in the shoes of a new user interested in purchasing one of your analyzers. He downloads the application and tries it in demo mode. Seeing random data is discouraging. Especially since there is no message in the user interface that tells him how to get interesting data. Will he think to check the documentation pages and restart with ENABLE_SIMULATION at 1?

Why didn't you put a check box in the preferences?

You write: "The reason we added this is because we simply haven't tested this feature completely yet". Okay, but the more this feature is used, the faster any bugs will be detected. Eventually, make the feature appear as a warning that it is not fully tested.

I suggest that the default behavior is to generate the specific data.

Best Regards,

Pierre Molinaro

**Comment by timreyes** [comment]
Hi Pierre, thanks for letting us know your feedback. You bring up a very valid point below:

> Okay, but the more this feature is used, the faster any bugs will be detected. Eventually, make the feature appear as a warning that it is not fully tested.

I do believe that generating analyzer-specific data is immensely more useful than random data. I'll go ahead and close this gitbook ticket now, but I'll be sure to get your specific feedback on our backlog to review.

Besides not having fully tested the feature yet, I believe there may be some other reasons our software team hasn't added this feature yet by default. The ENABLE_SIMULATION = 1 workaround is a hassle to both discover and to perform as a user who simply wants to run the software in this mode.
