### ISSUE TITLE
Merge exported files

### ISSUE THREAD

**Issue by Giants92** [saleae/gitbook-docs#35]
Hi !
Hardware : 8 channels/24 Mhz
Tested Card : Old School Computer (Amiga 1200)

On this old computer we have some tests points (28 to be exact)
Because I have only 8 channels, I get, with the same configuration under 'logic 2' software, a lot of 'mesure'.
5 to be exact and saved on .SAL  format.
On this 5 exports data, we have the identiq first channel (trigger of course, PowerOn VCC)
I would like to merge into 1 file and visualise all my capture on One screen under yout software 'logic 2'

I think it's possible to make a new 'meta.json' with all information of all my capture data (and so, rename it 1 to 28)
BUT...i see on each 'meta.json' some number and, I don't have exactly the same...
Exemple, extract file of myfirst Data : 

renderViewState":{"leftEdgeTimeSec":1.16268925,"timeSecPerPixel":0.011888941179366017},"captureProgress":{"maxCollectedTime":21.290666666666667,"processedInterval":{"begin":1.16268925,"end":21.290666666666667},"memoryUsedMb":325.30492973327637,"isProcessing":false,"triggerProgress":1.1626892083333333},"captureStartTime":{"unixTimeMilliseconds":1624995793493,"fractionalMilliseconds":0.7435}

Extract of my second data :
renderViewState":{"leftEdgeTimeSec":0.82114425,"timeSecPerPixel":0.01188906620397716},"captureProgress":{"maxCollectedTime":20.949333333333332,"processedInterval":{"begin":0.82114425,"end":20.949333333333332},"memoryUsedMb":515.3565607070923,"isProcessing":false,"triggerProgress":0.8211442083333333},"captureStartTime":{"unixTimeMilliseconds":1624995405187,"fractionalMilliseconds":0.9111}

See, it's not the same 'referencial'
So, How to merge All my captured data and see it on One uniq screen ?
Thks a lot

**Comment by timreyes** [comment]
Hi, thanks for writing this in. If I understand correctly, you have multiple .SAL capture files and you'd like to merge them? Unfortunately, we don't have this feature available.

Feel free to add this to our ideas page if that's the case! Other users haven't requested for this feature yet, and we can start tracking interest in this there before we add it to the roadmap.
https://ideas.saleae.com/b/feature-requests/

Also, we generally reserve posts on our Support site Github Issues list for documentation issues. I'll go ahead and close this now, but in case you need any further help with this, feel free to send me a message via the link below and we can discuss via a support ticket/email.
https://contact.saleae.com/hc/en-us/requests/new
