### ISSUE TITLE
Link to I2C.sal marked as not secure. 

### ISSUE THREAD

**Issue by fgr1986** [saleae/gitbook-docs#36]
Hi, the certificate of the link to the trace found at https://support.saleae.com/extensions/extensions-quickstart is marked as insecure by firefox, so the I2c.sal file is not available to the users

**Comment by timreyes** [comment]
Strange... I was able to download the file on Firefox. I'll go ahead and close this Issue for now, but I'd like to continue debugging this issue via email.

Can you send me a message using the link below?
https://contact.saleae.com/hc/en-us/requests/new

In your message, can you let me know if you are able to download the compliance docs below?
https://support.saleae.com/datasheets-and-specifications/compliance-documentation

**Comment by fgr1986** [comment]
Hi @timreyes  Just verified: from MacOS (firefox 89.0) no problem encountered.
Firefox 89.0 in Ubuntu is the one failing. I just filled the contact form you provided. 
Thanks
