### ISSUE TITLE
Feature Request: High Level Analyzers - Multiple Input Analyzers

### ISSUE THREAD

**Issue by nplus11** [saleae/gitbook-docs#37]
I noted there is no documentation or feature for multiple Input Analyzers to a HLA.
Can't find any repository where to requests this. Is this possible?

**Comment by timreyes** [comment]
Thanks for writing in this. We're tracking this idea below, and I went ahead and added a comment for you to track you need for it. I'll close this GitHub Issue for now. Feel free to vote on the idea below in the meantime!
https://ideas.saleae.com/b/feature-requests/high-level-analyzer-combine-data-from-multiple-sources/
