### ISSUE TITLE
The Device's USB VID and PID Failed

### ISSUE THREAD

**Issue by edahcag** [saleae/gitbook-docs#6]
The device always show vid 0x04b4 and pid 0x8613.

I already follow the webpage
https://trello.com/c/q2rMixk6/24-the-devices-usb-vid-and-pid-failed

I already try the steps below:
1. Change USB port
2. Remove the deivce again and again
3. Reboot the system

But, the vid/pid still is wrong.

What can I do?

**Comment by timreyes** [comment]
I'm so sorry about that! Please submit a warranty request below and we will be in touch:
https://saleae-support.typeform.com/to/E8UPB7
