### ISSUE TITLE
crash when observing a static signal

### ISSUE THREAD

**Issue by zegonix** [saleae/gitbook-docs#9]
im trying to capture two signals: data & envelope pin of a laser detector (ts4231)
sensor is configured lighthouse running -> works fine
i cover the light house -> software crashes instantly if i try to capture

**Comment by timreyes** [comment]
I'm so sorry for the trouble! Could you send me an email? (support@saleae.com).

In the email, please also share with me the details of the signal you are trying to capture. For example:
- Number of channels used
- Voltage levels
- What happens exactly (on the signal lines) when you cover the light house? I assume that a certain signal pattern is causing the crash, and I'd like to try and reproduce that pattern.
- Can you share the error report associated with the crash? The location of the error reports on your PC can be found at the bottom of the article below:
https://support.saleae.com/troubleshooting/software-has-crashed
